### ISSUE TITLE
IPv6 Incompatibility

### ISSUE THREAD

**Issue by laugimethods** [jboss-dockerfiles/jbpm#15]
On OS X version 10.11.6, to avoid the following fatal error when starting the jbpm Docker Image version 6.5.0.Final & 6.5.0.Final-1
```
15:43:12,773 ERROR [org.jboss.msc.service.fail] (MSC service thread 1-4) MSC000001: Failed to start service jboss.undertow.listener.default: org.jboss.msc.service.StartException in service jboss.undertow.listener.default: Could not start http listener
	at org.wildfly.extension.undertow.ListenerService.start(ListenerService.java:142)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1948)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1881)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.SocketException: Protocol family unavailable
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:433)
	at sun.nio.ch.Net.bind(Net.java:425)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at org.xnio.nio.NioXnioWorker.createTcpConnectionServer(NioXnioWorker.java:190)
	at org.xnio.XnioWorker.createStreamConnectionServer(XnioWorker.java:243)
	at org.wildfly.extension.undertow.HttpListenerService.startListening(HttpListenerService.java:126)
	at org.wildfly.extension.undertow.ListenerService.start(ListenerService.java:138)
	... 5 more
``` 
I had to specify `[docker run -p ...] -e JAVA_OPTS="-Xms256m -Xmx512m -Djava.net.preferIPv4Stack=true" [jboss/jbpm-workbench-showcase:6.5.0.Final-1]`.

It could also be done permanently by modifying the Dockerfile: `ENV JAVA_OPTS -Xms256m -Xmx512m -Djava.net.preferIPv4Stack=true`.

FYI:
```
> docker version
Client:
 Version:      17.05.0-ce-rc1
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   2878a85
 Built:        Tue Apr 11 20:55:05 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.05.0-ce-rc1
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   2878a85
 Built:        Tue Apr 11 20:55:05 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Comment by romartin** [comment]
Hey @laugimethods ,
Thanks for the feedback! There are other ways to do this too, please see [these comments](https://github.com/jboss-dockerfiles/jbpm/issues/17).
Thanks!

@mbiarnes Feel free to add more troubleshooting notes and close this issue. Thanks!

**Comment by Miggleness** [comment]
I had the same problem with MacOS.  The proposed solution of setting network=host didn't work.  Adding assignment for environment variable JAVA_OPTS="-Djava.net.preferIPv4Stack=true" resolved it for me

**Comment by romartin** [comment]
Hey  @miguelcudaihl , thanks for the feedback, just looking at https://github.com/jboss-dockerfiles/jbpm/pull/27 which applies this solution. Once verified we'll merge it, so this change will be available on the next release tag.
Thanks!

**Comment by tmhpfnr** [comment]
Worked like a charm
Thanks @Miggleness
