### ISSUE TITLE
java.io.IOException: Mount point not found error starting jbpm-workbench-showcase

### ISSUE THREAD

**Issue by ammianus** [jboss-dockerfiles/jbpm#22]
Starting docker container appears to have failures, and jbpm-console application is not accessible even after the container appears to be running.

Tried following steps here:
https://hub.docker.com/r/jboss/jbpm-workbench-showcase/

I am using Docker for Mac: 
Version 17.09.0-ce-mac34 (19605)
Channel: edge
c076099f52

I do use Docker for other applications, but no other containers are running while trying this.

The command I have tried includes the --network="host" mentioned in the troubleshooting and other steps.

`docker run -i -t -p 8080:8080 -p 8001:8001 -d --network="host" --name jbpm-workbench jboss/jbpm-workbench:latest`

From the docker logs I see this error (and a couple other stack traces earlier in the logs)
```
15:32:41,563 ERROR [stderr] (management-handler-thread - 3) java.io.IOException: Mount point not found
15:32:41,563 ERROR [stderr] (management-handler-thread - 3) 	at sun.nio.fs.LinuxFileStore.findMountEntry(LinuxFileStore.java:91)
15:32:41,564 ERROR [stderr] (management-handler-thread - 3) 	at sun.nio.fs.UnixFileStore.<init>(UnixFileStore.java:65)
15:32:41,564 ERROR [stderr] (management-handler-thread - 3) 	at sun.nio.fs.LinuxFileStore.<init>(LinuxFileStore.java:44)
15:32:41,564 ERROR [stderr] (management-handler-thread - 3) 	at sun.nio.fs.LinuxFileSystemProvider.getFileStore(LinuxFileSystemProvider.java:51)
15:32:41,564 ERROR [stderr] (management-handler-thread - 3) 	at sun.nio.fs.LinuxFileSystemProvider.getFileStore(LinuxFileSystemProvider.java:39)
15:32:41,564 ERROR [stderr] (management-handler-thread - 3) 	at sun.nio.fs.UnixFileSystemProvider.getFileStore(UnixFileSystemProvider.java:368)
15:32:41,564 ERROR [stderr] (management-handler-thread - 3) 	at java.nio.file.Files.getFileStore(Files.java:1461)
15:32:41,565 ERROR [stderr] (management-handler-thread - 3) 	at org.jboss.as.controller.persistence.FilePersistenceUtils.getPosixAttributes(FilePersistenceUtils.java:124)
15:32:41,565 ERROR [stderr] (management-handler-thread - 3) 	at org.jboss.as.controller.persistence.FilePersistenceUtils.createTempFileWithAttributes(FilePersistenceUtils.java:112)
15:32:41,565 ERROR [stderr] (management-handler-thread - 3) 	at org.jboss.as.controller.persistence.FilePersistenceUtils.writeToTempFile(FilePersistenceUtils.java:99)
15:32:41,565 ERROR [stderr] (management-handler-thread - 3) 	at org.jboss.as.controller.persistence.ConfigurationFilePersistenceResource.doCommit(ConfigurationFilePersistenceResource.java:55)
15:32:41,566 ERROR [stderr] (management-handler-thread - 3) 	at org.jboss.as.controller.persistence.AbstractFilePersistenceResource.commit(AbstractFilePersistenceResource.java:58)
15:32:41,566 ERROR [stderr] (management-handler-thread - 3) 	at org.jboss.as.controller.ModelControllerImpl$4.commit(ModelControllerImpl.java:789)
15:32:41,566 ERROR [stderr] (management-handler-thread - 3) 	at org.jboss.as.controller.AbstractOperationContext.executeDoneStage(AbstractOperationContext.java:743)
15:32:41,566 ERROR [stderr] (management-handler-thread - 3) 	at org.jboss.as.controller.AbstractOperationContext.processStages(AbstractOperationContext.java:680)
15:32:41,566 ERROR [stderr] (management-handler-thread - 3) 	at org.jboss.as.controller.AbstractOperationContext.executeOperation(AbstractOperationContext.java:370)
15:32:41,567 ERROR [stderr] (management-handler-thread - 3) 	at org.jboss.as.controller.OperationContextImpl.executeOperation(OperationContextImpl.java:1329)
15:32:41,567 ERROR [stderr] (management-handler-thread - 3) 	at org.jboss.as.controller.ModelControllerImpl.internalExecute(ModelControllerImpl.java:400)
15:32:41,568 ERROR [stderr] (management-handler-thread - 3) 	at org.jboss.as.controller.ModelControllerImpl.execute(ModelControllerImpl.java:222)
15:32:41,568 ERROR [stderr] (management-handler-thread - 3) 	at org.jboss.as.controller.remote.ModelControllerClientOperationHandler$ExecuteRequestHandler.doExecute(ModelControllerClientOperationHandler.java:208)
15:32:41,568 ERROR [stderr] (management-handler-thread - 3) 	at org.jboss.as.controller.remote.ModelControllerClientOperationHandler$ExecuteRequestHandler.access$300(ModelControllerClientOperationHandler.java:130)
15:32:41,568 ERROR [stderr] (management-handler-thread - 3) 	at org.jboss.as.controller.remote.ModelControllerClientOperationHandler$ExecuteRequestHandler$1$1.run(ModelControllerClientOperationHandler.java:152)
15:32:41,568 ERROR [stderr] (management-handler-thread - 3) 	at org.jboss.as.controller.remote.ModelControllerClientOperationHandler$ExecuteRequestHandler$1$1.run(ModelControllerClientOperationHandler.java:148)
15:32:41,569 ERROR [stderr] (management-handler-thread - 3) 	at java.security.AccessController.doPrivileged(Native Method)
15:32:41,569 ERROR [stderr] (management-handler-thread - 3) 	at javax.security.auth.Subject.doAs(Subject.java:422)
15:32:41,569 ERROR [stderr] (management-handler-thread - 3) 	at org.jboss.as.controller.AccessAuditContext.doAs(AccessAuditContext.java:149)
15:32:41,569 ERROR [stderr] (management-handler-thread - 3) 	at org.jboss.as.controller.remote.ModelControllerClientOperationHandler$ExecuteRequestHandler$1.execute(ModelControllerClientOperationHandler.java:148)
15:32:41,569 ERROR [stderr] (management-handler-thread - 3) 	at org.jboss.as.protocol.mgmt.AbstractMessageHandler$ManagementRequestContextImpl$1.doExecute(AbstractMessageHandler.java:363)
15:32:41,570 ERROR [stderr] (management-handler-thread - 3) 	at org.jboss.as.protocol.mgmt.AbstractMessageHandler$AsyncTaskRunner.run(AbstractMessageHandler.java:472)
15:32:41,570 ERROR [stderr] (management-handler-thread - 3) 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
15:32:41,570 ERROR [stderr] (management-handler-thread - 3) 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
15:32:41,570 ERROR [stderr] (management-handler-thread - 3) 	at java.lang.Thread.run(Thread.java:748)
15:32:41,570 ERROR [stderr] (management-handler-thread - 3) 	at org.jboss.threads.JBossThread.run(JBossThread.java:320)
15:32:41,572 INFO  [org.jboss.as.server] (management-handler-thread - 3) WFLYSRV0010: Deployed "kie#postgresql-9.4.1207#" (runtime-name : "kie#postgresql-9.4.1207#")
15:32:41,628 INFO  [org.kie.workbench.common.screens.datasource.management.backend.DataSourceManagementBootstrap] (pool-11-thread-1) Initialize deployments task finished successfully.
```

Note: I also tried literally using `--network="host .."` as indicated in the troubleshooting steps, but I don't think the extra .. are correct, it fails with a different error:
```
docker: Error response from daemon: No such network: host ..
```

**Comment by mbiarnes** [comment]
Hi
Tested here and it works perfectly.
It was used the docker version 1.8.2-fc22.
It seems that in this version it is not --network anymore, now it is --net.
Are you sure that your port is still free?

**Comment by Pawkuzmi** [comment]
`Mount point not found` error is sometimes connected with different storage drivers. For instance someone uses this image on docker with storage driver `aufs`. For him it may work perfectly, however other user, with storage driver `overlay2` may encounter this issue. Try:
`docker info`
and check which storage driver You use. If it's `overlay2` that may be the reason
