### ISSUE TITLE
Could not start 'default' listener

### ISSUE THREAD

**Issue by trahloff** [jboss-dockerfiles/jbpm#26]
After copy-pasting the recommended start command 
`docker run -p 8080:8080 -p 8001:8001 -d --name jbpm-workbench3 jboss/jbpm-workbench:latest`
the container won't crash but can't be accessed either.

The Error:

```
10:51:48,056 ERROR [org.jboss.msc.service.fail] (MSC service thread 1-1) MSC000001: Failed to start service jboss.undertow.listener.default: org.jboss.msc.service.StartException in service jboss.undertow.listener.default: WFLYUT0082: Could not start 'default' listener.
	at org.wildfly.extension.undertow.ListenerService.start(ListenerService.java:153)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1948)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1881)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.SocketException: Protocol family unavailable
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:433)
	at sun.nio.ch.Net.bind(Net.java:425)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at org.xnio.nio.NioXnioWorker.createTcpConnectionServer(NioXnioWorker.java:190)
	at org.xnio.XnioWorker.createStreamConnectionServer(XnioWorker.java:243)
	at org.wildfly.extension.undertow.HttpListenerService.startListening(HttpListenerService.java:126)
	at org.wildfly.extension.undertow.ListenerService.start(ListenerService.java:142)
	... 5 more

10:51:48,143 INFO  [org.wildfly.iiop.openjdk] (MSC service thread 1-7) WFLYIIOP0009: CORBA ORB Service started
10:51:48,216 WARN  [org.jboss.as.domain.management.security] (MSC service thread 1-2) WFLYDM0111: Keystore /opt/jboss/wildfly/standalone/configuration/application.keystore not found, it will be auto generated on first use with a self signed certificate for host localhost
10:51:48,222 INFO  [org.jboss.as.connector.subsystems.datasources] (MSC service thread 1-5) WFLYJCA0001: Bound data source [java:jboss/datasources/ExampleDS]
10:51:48,235 INFO  [org.jboss.as.server.deployment.scanner] (MSC service thread 1-5) WFLYDS0013: Started FileSystemDeploymentService for directory /opt/jboss/wildfly/standalone/deployments
10:51:48,237 INFO  [org.jboss.as.server.deployment] (MSC service thread 1-1) WFLYSRV0027: Starting deployment of "jbpm-console.war" (runtime-name: "jbpm-console.war")
10:51:48,367 ERROR [org.jboss.msc.service.fail] (MSC service thread 1-1) MSC000001: Failed to start service jboss.undertow.listener.https: org.jboss.msc.service.StartException in service jboss.undertow.listener.https: WFLYUT0082: Could not start 'https' listener.
	at org.wildfly.extension.undertow.ListenerService.start(ListenerService.java:153)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1948)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1881)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.SocketException: Protocol family unavailable
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:433)
	at sun.nio.ch.Net.bind(Net.java:425)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at org.xnio.nio.NioXnioWorker.createTcpConnectionServer(NioXnioWorker.java:190)
	at org.xnio.XnioWorker.createStreamConnectionServer(XnioWorker.java:243)
	at io.undertow.protocols.ssl.UndertowXnioSsl.createSslConnectionServer(UndertowXnioSsl.java:301)
	at org.wildfly.extension.undertow.HttpsListenerService.startListening(HttpsListenerService.java:125)
	at org.wildfly.extension.undertow.ListenerService.start(ListenerService.java:142)
	... 5 more

10:51:48,390 INFO  [org.infinispan.factories.GlobalComponentRegistry] (MSC service thread 1-6) ISPN000128: Infinispan version: Infinispan 'Chakra' 8.2.4.Final
10:51:48,420 INFO  [org.infinispan.configuration.cache.EvictionConfigurationBuilder] (ServerService Thread Pool -- 68) ISPN000152: Passivation configured without an eviction policy being selected. Only manually evicted entities will be passivated.
10:51:48,420 INFO  [org.infinispan.configuration.cache.EvictionConfigurationBuilder] (ServerService Thread Pool -- 64) ISPN000152: Passivation configured without an eviction policy being selected. Only manually evicted entities will be passivated.
10:51:48,421 INFO  [org.infinispan.configuration.cache.EvictionConfigurationBuilder] (ServerService Thread Pool -- 68) ISPN000152: Passivation configured without an eviction policy being selected. Only manually evicted entities will be passivated.
10:51:48,421 INFO  [org.infinispan.configuration.cache.EvictionConfigurationBuilder] (ServerService Thread Pool -- 64) ISPN000152: Passivation configured without an eviction policy being selected. Only manually evicted entities will be passivated.
10:51:48,426 INFO  [org.infinispan.configuration.cache.EvictionConfigurationBuilder] (ServerService Thread Pool -- 65) ISPN000152: Passivation configured without an eviction policy being selected. Only manually evicted entities will be passivated.
10:51:48,427 INFO  [org.infinispan.configuration.cache.EvictionConfigurationBuilder] (ServerService Thread Pool -- 65) ISPN000152: Passivation configured without an eviction policy being selected. Only manually evicted entities will be passivated.
10:51:55,468 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-5) WFLYSRV0059: Class Path entry jaxb-core.jar in /opt/jboss/wildfly/standalone/deployments/jbpm-console.war/WEB-INF/lib/jaxb-impl-2.2.11.jar  does not point to a valid jar for a Class-Path reference.
10:51:55,473 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-5) WFLYSRV0059: Class Path entry xml-apis.jar in /opt/jboss/wildfly/standalone/deployments/jbpm-console.war/WEB-INF/lib/serializer-2.7.1.jar  does not point to a valid jar for a Class-Path reference.
10:51:55,481 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-5) WFLYSRV0059: Class Path entry xercesImpl.jar in /opt/jboss/wildfly/standalone/deployments/jbpm-console.war/WEB-INF/lib/xalan-2.7.1.jar  does not point to a valid jar for a Class-Path reference.
10:51:55,481 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-5) WFLYSRV0059: Class Path entry xml-apis.jar in /opt/jboss/wildfly/standalone/deployments/jbpm-console.war/WEB-INF/lib/xalan-2.7.1.jar  does not point to a valid jar for a Class-Path reference.
10:51:55,481 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-5) WFLYSRV0059: Class Path entry serializer.jar in /opt/jboss/wildfly/standalone/deployments/jbpm-console.war/WEB-INF/lib/xalan-2.7.1.jar  does not point to a valid jar for a Class-Path reference.
10:51:55,496 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-5) WFLYSRV0059: Class Path entry jaxb-api.jar in /opt/jboss/wildfly/standalone/deployments/jbpm-console.war/WEB-INF/lib/jaxb-core-2.2.11.jar  does not point to a valid jar for a Class-Path reference.
10:51:55,580 ERROR [org.jboss.as.controller.management-operation] (Controller Boot Thread) WFLYCTL0013: Operation ("deploy") failed - address: ([("deployment" => "jbpm-console.war")]) - failure description: {
    "WFLYCTL0180: Services with missing/unavailable dependencies" => undefined,
    "WFLYCTL0288: One or more services were unable to start due to one or more indirect dependencies not being available." => {
        "Services that were unable to start:" => ["jboss.deployment.unit.\"jbpm-console.war\".PARSE"],
        "Services that may be the cause:" => [
            "jboss.http-upgrade-registry.default",
            "jboss.remoting.remotingConnectorInfoService.http-remoting-connector"
        ]
    }
}
10:51:55,582 ERROR [org.jboss.as.controller.management-operation] (Controller Boot Thread) WFLYCTL0013: Operation ("add") failed - address: ([("subsystem" => "jsr77")]) - failure description: {
    "WFLYCTL0180: Services with missing/unavailable dependencies" => undefined,
    "WFLYCTL0288: One or more services were unable to start due to one or more indirect dependencies not being available." => {
        "Services that were unable to start:" => ["jboss.jsr77.ejb"],
        "Services that may be the cause:" => [
            "jboss.http-upgrade-registry.default",
            "jboss.remoting.remotingConnectorInfoService.http-remoting-connector"
        ]
    }
}
10:51:55,583 ERROR [org.jboss.as.controller.management-operation] (Controller Boot Thread) WFLYCTL0013: Operation ("add") failed - address: ([
    ("subsystem" => "undertow"),
    ("server" => "default-server"),
    ("http-listener" => "default")
]) - failure description: {
    "WFLYCTL0080: Failed services" => {"jboss.undertow.listener.default" => "org.jboss.msc.service.StartException in service jboss.undertow.listener.default: WFLYUT0082: Could not start 'default' listener.
    Caused by: java.net.SocketException: Protocol family unavailable"},
    "WFLYCTL0412: Required services that are not installed:" => ["jboss.undertow.listener.default"],
    "WFLYCTL0180: Services with missing/unavailable dependencies" => undefined
}
10:51:55,583 ERROR [org.jboss.as.controller.management-operation] (Controller Boot Thread) WFLYCTL0013: Operation ("add") failed - address: ([("subsystem" => "ejb3")]) - failure description: {
    "WFLYCTL0180: Services with missing/unavailable dependencies" => undefined,
    "WFLYCTL0288: One or more services were unable to start due to one or more indirect dependencies not being available." => {
        "Services that were unable to start:" => [
            "jboss.ejb.default-local-ejb-receiver-service",
            "jboss.ejb3.ejbClientContext.default",
            "jboss.ejb3.localEjbReceiver.value"
        ],
        "Services that may be the cause:" => [
            "jboss.http-upgrade-registry.default",
            "jboss.remoting.remotingConnectorInfoService.http-remoting-connector"
        ]
    }
}
10:51:55,583 ERROR [org.jboss.as.controller.management-operation] (Controller Boot Thread) WFLYCTL0013: Operation ("add") failed - address: ([
    ("subsystem" => "undertow"),
    ("server" => "default-server"),
    ("https-listener" => "https")
]) - failure description: {
    "WFLYCTL0080: Failed services" => {"jboss.undertow.listener.https" => "org.jboss.msc.service.StartException in service jboss.undertow.listener.https: WFLYUT0082: Could not start 'https' listener.
    Caused by: java.net.SocketException: Protocol family unavailable"},
    "WFLYCTL0412: Required services that are not installed:" => ["jboss.undertow.listener.https"],
    "WFLYCTL0180: Services with missing/unavailable dependencies" => undefined
}
10:51:55,584 ERROR [org.jboss.as.controller.management-operation] (Controller Boot Thread) WFLYCTL0013: Operation ("add") failed - address: ([("subsystem" => "webservices")]) - failure description: {
    "WFLYCTL0180: Services with missing/unavailable dependencies" => undefined,
    "WFLYCTL0288: One or more services were unable to start due to one or more indirect dependencies not being available." => {
        "Services that were unable to start:" => ["jboss.ws.config"],
        "Services that may be the cause:" => [
            "jboss.http-upgrade-registry.default",
            "jboss.remoting.remotingConnectorInfoService.http-remoting-connector"
        ]
    }
}
10:51:55,585 ERROR [org.jboss.as.controller.management-operation] (Controller Boot Thread) WFLYCTL0013: Operation ("add") failed - address: ([
    ("subsystem" => "messaging-activemq"),
    ("server" => "default")
]) - failure description: {
    "WFLYCTL0412: Required services that are not installed:" => ["jboss.http-upgrade-registry.default"],
    "WFLYCTL0180: Services with missing/unavailable dependencies" => ["jboss.messaging-activemq.default is missing [jboss.http-upgrade-registry.default]"],
    "WFLYCTL0288: One or more services were unable to start due to one or more indirect dependencies not being available." => {
        "Services that were unable to start:" => ["jboss.messaging-activemq.default.jms.manager"],
        "Services that may be the cause:" => [
            "jboss.http-upgrade-registry.default",
            "jboss.remoting.remotingConnectorInfoService.http-remoting-connector"
        ]
    }
}
10:51:55,596 ERROR [org.jboss.as.controller.management-operation] (Controller Boot Thread) WFLYCTL0013: Operation ("add") failed - address: ([
    ("subsystem" => "ejb3"),
    ("service" => "remote")
]) - failure description: {
    "WFLYCTL0412: Required services that are not installed:" => ["jboss.remoting.remotingConnectorInfoService.http-remoting-connector"],
    "WFLYCTL0180: Services with missing/unavailable dependencies" => ["jboss.ejb3.connector is missing [jboss.remoting.remotingConnectorInfoService.http-remoting-connector]"]
}
10:51:55,611 INFO  [org.jboss.as.server] (ServerService Thread Pool -- 37) WFLYSRV0010: Deployed "jbpm-console.war" (runtime-name : "jbpm-console.war")
10:51:55,614 INFO  [org.jboss.as.controller] (Controller Boot Thread) WFLYCTL0183: Service status report
WFLYCTL0184:    New missing/unsatisfied dependencies:
      service jboss.http-upgrade-registry.default (missing) dependents: [service jboss.messaging-activemq.default] 
      service jboss.remoting.remotingConnectorInfoService.http-remoting-connector (missing) dependents: [service jboss.ejb3.connector] 
WFLYCTL0186:   Services which failed to start:      service jboss.undertow.listener.https: org.jboss.msc.service.StartException in service jboss.undertow.listener.https: WFLYUT0082: Could not start 'https' listener.
      service jboss.undertow.listener.default: org.jboss.msc.service.StartException in service jboss.undertow.listener.default: WFLYUT0082: Could not start 'default' listener.

10:51:55,676 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0060: Http management interface listening on http://127.0.0.1:9990/management
10:51:55,677 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0051: Admin console listening on http://127.0.0.1:9990
10:51:55,677 ERROR [org.jboss.as] (Controller Boot Thread) WFLYSRV0026: WildFly Full 10.1.0.Final (WildFly Core 2.2.0.Final) started (with errors) in 9616ms - Started 340 of 610 services (11 services failed or missing dependencies, 407 services are lazy, passive or on-demand)
10:51:55,835 INFO  [org.jboss.as.server.deployment] (MSC service thread 1-5) WFLYSRV0028: Stopped deployment jbpm-console.war (runtime-name: jbpm-console.war) in 142ms
10:51:55,875 WARN  [org.jboss.as.controller] (DeploymentScanner-threads - 1) WFLYCTL0357: Notification of type deployment-undeployed is not described for the resource at the address []
10:51:55,876 INFO  [org.jboss.as.server] (DeploymentScanner-threads - 1) WFLYSRV0009: Undeployed "jbpm-console.war" (runtime-name: "jbpm-console.war")
10:51:55,877 INFO  [org.jboss.as.controller] (DeploymentScanner-threads - 1) WFLYCTL0183: Service status report
WFLYCTL0186:   Services which failed to start:      service jboss.undertow.listener.https: org.jboss.msc.service.StartException in service jboss.undertow.listener.https: WFLYUT0082: Could not start 'https' listener.
      service jboss.undertow.listener.default: org.jboss.msc.service.StartException in service jboss.undertow.listener.default: WFLYUT0082: Could not start 'default' listener.

10:52:00,630 INFO  [org.jboss.as.server.deployment.scanner] (DeploymentScanner-threads - 1) WFLYDS0004: Found jbpm-console.war in deployment directory. To trigger deployment create a file called jbpm-console.war.dodeploy
```

**Comment by mbiarnes** [comment]
Hi,

This is error is new to us.
we tested the run of the containers in our environment and everything works properly.
If you want to run jbpm-workbench (base) and not the jbpm-workbench-showcase you have to create a user first so thta you can access. For this the images has to be started in /bin/bash mode so you can create a user with ./bin/createUser.sh .
I recommend you to start jbpm-workbench-showcase since you have users predefined here and you can access.

**Comment by mbiarnes** [comment]
tested again -worked for me on Fedora 27 and docker version: Docker version 1.13.1
Which docker version are you using?

**Comment by spolti** [comment]
Maybe it is related to https://github.com/jboss-dockerfiles/jbpm/issues/15 ?

**Comment by hiphipis** [comment]
Have same problem with Docker 17.12.0-ce-win47 on Windows 10Pro.
IP4 hack mentioned above helped to solve.

**Comment by Teg79** [comment]
I have the same problem running wildfly from his maven plugin on a eclipse-che workspace (the java-maven-tomcat8 stack)

**Comment by wilferraciolli** [comment]
Passing the "-Djava.net.preferIPv4Stack=true" argument to the JVM has fixed my problem
