### ISSUE TITLE
Communication issue between jbpm-workbench-showcase and kie-server-showcase

### ISSUE THREAD

**Issue by SimonRinguette** [jboss-dockerfiles/jbpm#29]
Working with tag 7.5.0.Final.

I'm running the jbpm-workbench-showcase docker using:

`docker run -p 8080:8080 -p 8001:8001 -d -e JAVA_OPTS="-Djava.net.preferIPv4Stack=true" --name jbpm-workbench jboss/jbpm-workbench-showcase:latest`

I'm running the kie-server-showcase docker using:
`docker run -p 8180:8080 -d --name kie-server -e JAVA_OPTS="-Djava.net.preferIPv4Stack=true" --link jbpm-workbench:kie_wb jboss/kie-server-showcase:latest`

Everything works find until I try to access the Manage and Track options of jBPM execution. For instance clicking on Manage->Process Instance will give me the following error:

`Process Definitions could not be loaded. Check if the jBPM Capabilities are enabled and if the remote server is correctly set up.`

Looking at the logs of the kie-server-showcase container, I'm not seeing anything.

Looking at the logs of the jbpm-workbench-showcase container I get:

`13:47:07,683 ERROR [org.dashbuilder.exception.ExceptionManager] (default task-18) Can't lookup on specified data set: jbpmProcessInstances: org.dashbuilder.dataset.exception.DataSetLookupException: Can't lookup on specified data set: jbpmProcessInstances
        at org.dashbuilder.dataset.DataSetManagerImpl.lookupDataSet(DataSetManagerImpl.java:156)
        at org.dashbuilder.dataset.DataSetManagerCDI$Proxy$_$$_WeldClientProxy.lookupDataSet(Unknown Source)
        at org.dashbuilder.dataset.service.DataSetLookupServicesImpl.lookupDataSet(DataSetLookupServicesImpl.java:78)
        at org.dashbuilder.dataset.service.DataSetLookupServicesImpl$Proxy$_$$_WeldClientProxy.lookupDataSet(Unknown Source)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jboss.errai.bus.server.io.AbstractRPCMethodCallback.invokeMethodFromMessage(AbstractRPCMethodCallback.java:65)
        at org.jboss.errai.bus.server.io.ValueReplyRPCEndpointCallback.callback(ValueReplyRPCEndpointCallback.java:40)
        at org.jboss.errai.bus.server.io.RemoteServiceCallback.callback(RemoteServiceCallback.java:54)
        at org.jboss.errai.cdi.server.CDIExtensionPoints$2.callback(CDIExtensionPoints.java:448)
        at org.jboss.errai.bus.server.DeliveryPlan.deliver(DeliveryPlan.java:47)
        at org.jboss.errai.bus.server.ServerMessageBusImpl.sendGlobal(ServerMessageBusImpl.java:297)
        at org.jboss.errai.bus.server.SimpleDispatcher.dispatchGlobal(SimpleDispatcher.java:46)
        at org.jboss.errai.bus.server.service.ErraiServiceImpl.store(ErraiServiceImpl.java:96)
        at org.jboss.errai.bus.server.service.ErraiServiceImpl.store(ErraiServiceImpl.java:113)
        at org.jboss.errai.bus.server.servlet.DefaultBlockingServlet.doPost(DefaultBlockingServlet.java:144)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:85)
        at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)
        at io.undertow.websockets.jsr.JsrWebSocketFilter.doFilter(JsrWebSocketFilter.java:130)
        at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
        at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
        at org.uberfire.ext.security.server.SecureHeadersFilter.doFilter(SecureHeadersFilter.java:110)
        at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
        at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
        at org.uberfire.ext.security.server.SecurityIntegrationFilter.doFilter(SecurityIntegrationFilter.java:70)
        at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
        at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
        at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
        at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
        at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
        at org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:131)
        at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
        at io.undertow.server.handlers.DisableCacheHandler.handleRequest(DisableCacheHandler.java:33)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at io.undertow.security.handlers.AuthenticationConstraintHandler.handleRequest(AuthenticationConstraintHandler.java:53)
        at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
        at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
        at io.undertow.servlet.handlers.security.ServletSecurityConstraintHandler.handleRequest(ServletSecurityConstraintHandler.java:59)
        at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
        at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
        at io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
        at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:292)
        at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:81)
        at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:138)
        at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:135)
        at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
        at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
        at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
        at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
        at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
        at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
        at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
        at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:272)
        at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:81)
        at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:104)
        at io.undertow.server.Connectors.executeRootHandler(Connectors.java:202)
        at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:805)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.kie.server.common.rest.KieServerHttpRequestException: Unable to retrieve input stream of response
        at org.kie.server.common.rest.KieServerHttpRequest.responseStream(KieServerHttpRequest.java:1389)
        at org.kie.server.common.rest.KieServerHttpRequest.responseBuffer(KieServerHttpRequest.java:1407)
        at org.kie.server.common.rest.KieServerHttpRequest.responseBody(KieServerHttpRequest.java:1349)
        at org.kie.server.common.rest.KieServerHttpRequest.access$2100(KieServerHttpRequest.java:117)
        at org.kie.server.common.rest.KieServerHttpRequest$5.body(KieServerHttpRequest.java:1315)
        at org.kie.server.client.impl.AbstractKieServicesClientImpl.createExceptionForUnexpectedResponseCode(AbstractKieServicesClientImpl.java:615)
        at org.kie.server.client.impl.AbstractKieServicesClientImpl.makeHttpPostRequestAndCreateCustomResponse(AbstractKieServicesClientImpl.java:320)
        at org.kie.server.client.impl.AbstractKieServicesClientImpl.makeHttpPostRequestAndCreateCustomResponse(AbstractKieServicesClientImpl.java:300)
        at org.kie.server.client.impl.QueryServicesClientImpl.query(QueryServicesClientImpl.java:949)
        at org.jbpm.workbench.ks.integration.KieServerDataSetProvider.lookupDataSet(KieServerDataSetProvider.java:159)
        at org.jbpm.workbench.ks.integration.KieServerDataSetProvider$Proxy$_$$_WeldClientProxy.lookupDataSet(Unknown Source)
        at org.dashbuilder.dataset.DataSetManagerImpl.lookupDataSet(DataSetManagerImpl.java:154)
        ... 70 more
Caused by: java.net.HttpRetryException: cannot retry due to server authentication, in streaming mode
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1692)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
        at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
        at org.kie.server.common.rest.KieServerHttpRequest.responseCode(KieServerHttpRequest.java:1329)
        at org.kie.server.common.rest.KieServerHttpRequest.post(KieServerHttpRequest.java:719)
        at org.kie.server.client.impl.AbstractKieServicesClientImpl$6.doOperation(AbstractKieServicesClientImpl.java:308)
        at org.kie.server.client.impl.AbstractKieServicesClientImpl.invoke(AbstractKieServicesClientImpl.java:804)
        at org.kie.server.client.impl.AbstractKieServicesClientImpl.makeHttpPostRequestAndCreateCustomResponse(AbstractKieServicesClientImpl.java:305)
        ... 75 more`

I'm guessing this has something to do with the authentication with the kie-server... i double checked and the kie-server REST api is reponsive under /kie-server/services/rest/server/ using the default kieserver/kieserver1! credentials and show BPM as a capability.

I'm running docker for windows:
`Client:
 Version:       17.12.0-ce
 API version:   1.35
 Go version:    go1.9.2
 Git commit:    c97c6d6
 Built: Wed Dec 27 20:05:22 2017
 OS/Arch:       windows/amd64

Server:
 Engine:
  Version:      17.12.0-ce
  API version:  1.35 (minimum version 1.12)
  Go version:   go1.9.2
  Git commit:   c97c6d6
  Built:        Wed Dec 27 20:12:29 2017
  OS/Arch:      linux/amd64
  Experimental: true`

Also tried with the same result on ubuntu.

**Comment by preston** [comment]
The `--link` option is legacy, and I'm not sure what the support status of it is. Could that have something to do with it?

**Comment by SimonRinguette** [comment]
This is coming from the documentation at https://hub.docker.com/r/jboss/kie-server-showcase/

**Comment by preston** [comment]
Not sure if it's causal to the issue.. just pointing it out. Sounds like the way the application integration is configured will need to change. The [Docker documentation](https://docs.docker.com/engine/userguide/networking/default_network/dockerlinks/) says:

> Unless you absolutely need to continue using it, we recommend that you use user-defined networks to facilitate communication between two containers instead of using --link.

**Comment by hiphipis** [comment]
Same on the Linux Docker version 17.12.0-ce.

Don't think it is related to the network configuration: I can run bash inside containers to successfully ping each other and nicely curl default wildfly page (aka http://*:8080/). Also I see kie-server registered in the workbench and sample project "itorders" gets deployed on kie-server:

```
12:43:17,431 INFO  [org.jbpm.kie.services.impl.query.QueryServiceImpl] (default task-10) Registered jbpmHumanTasksWithUser query successfully 
12:49:47,188 WARN  [org.appformer.maven.integration.embedder.MavenSettings] (default task-15) Environment variable M2_HOME is not set
12:49:47,406 INFO  [org.appformer.maven.integration.Aether] (default task-15) The local repository directory /opt/jboss/.m2/repository doesn't exist. Creating it.
12:49:55,710 INFO  [org.drools.compiler.kie.builder.impl.KieRepositoryImpl] (default task-15) KieModule was added: ZipKieModule[releaseId=itorders:itorders:1.0.0-SNAPSHOT,file=/opt/jboss/.m2/repository/itorders/itorders/1.0.0-SNAPSHOT/itorders-1.0.0-SNAPSHOT.jar]
12:49:57,690 INFO  [org.kie.server.services.impl.KieServerImpl] (default task-15) Container itorders_1.0.0-SNAPSHOT (for release id itorders:itorders:1.0.0-SNAPSHOT) successfully started
```
But any attempt to get any process related information produces exception at jbpm-wb similar to the one on the first post:
`
12:51:28,024 ERROR [org.dashbuilder.exception.ExceptionManager] (default task-47) Can't lookup on specified data set: jbpmHumanTasksWithUser: org.dashbuilder.dataset.exception.DataSetLookupException: Can't lookup on specified data set: jbpmHumanTasksWithUser
`

**Comment by stuba** [comment]
Im facing same issues here. Any ideas how to fix this?

**Comment by preston** [comment]
I’m curious if *anyone* is running these images successfully.

**Comment by RavinandanNaik** [comment]
I just encountered the problem today
`HttpRetryException: cannot retry due to server authentication, in streaming mode`
Its reported here as well - https://groups.google.com/forum/#!topic/jbpm-development/Wik3FA_AQ1s

**Comment by romartin** [comment]
Hello @SimonRinguette @preston @stuba @RavinandanNaik 

Sorry for late response. A few comments:

- The `--link` option specified in the docs is necessary if you're running the images as the docs suggest, that's because when liking containers the Docker deamon is setting some environment stuff, which is actually being used by some scripts for running and integrating the containers. I'm agree with you about now Docker recommends not using this approach, so we could try to improve this, anyway let you know it's done this way just because this was looking good time ago when Docker was not so powerful :)

- So it seems there exist an issue with the `7.5.0.Final` version, right? Can someone confirm that the fix is about adding some missing configuration in the standalone configuration file, as [this link](https://groups.google.com/forum/#!topic/jbpm-development/Wik3FA_AQ1s) describes? 

Please @mbiarnes can you try to reproduce it and see if it affects newer versions too? You should be able to do it by just following the docs and running both containers with the `--link` option, etc etc. If you are able to reproduce it, can you please check the fix proposed too?? Lemme know if I can help

Thanks in advance!

**Comment by mbiarnes** [comment]
hi Roger,
I can't reproduce it in 7.7.0.Final. I tried to follow what  Simon said, but it work correctly.

**Comment by RavinandanNaik** [comment]
Hey, 
I pulled 7.7.0 (wb and kie-server) yesterday and tested.
Process instance loads correctly after deploying sample project

**Comment by romartin** [comment]
Thanks @mbiarnes @RavinandanNaik 
So @SimonRinguette  it seems the bug could be just on the `7.5.0.Final` version... can you please report a bug for it (by opening a new ticket in https://issues.jboss.org/, you can use the `JBPM` as project)? We'll try to address it ASAP, otherwise if it's good for you, you upgrade to `7.7.0.Final` as it seems it's working.
Thanks!

**Comment by NullVoxPopuli** [comment]
@SimonRinguette did you ever get the kie api working with your setup?

**Comment by NullVoxPopuli** [comment]
@RavinandanNaik do you have a docker-compose setup? I'm having issues getting deployed projects to show up in kie-server's containers endpoint

**Comment by RavinandanNaik** [comment]
Unfortunately no. I used plain docker commands as mentioned in wb and kie-server (showcase) docker pages.

**Comment by NullVoxPopuli** [comment]
@RavinandanNaik  ah. how'd you get the project deployed to kie-server? (I can translate to compose from docker commands)

**Comment by RavinandanNaik** [comment]
@NullVoxPopuli 
As I mentioned i just followed the commands mentioned in showcase docker pages of jbpm-wb and kie-server
```
$docker images
jboss/jbpm-workbench-showcase   latest              a32defdb91a4        11 days ago         829MB
jboss/kie-server-showcase       latest              c5c7c6de9d24        11 days ago         774MB

$docker run -p 8080:8080 -p 8001:8001 -e JAVA_OPTS="-Xms512m -Xmx1G -Djava.net.preferIPv4Stack=true" jboss/jbpm-workbench-showcase
$docker run -p 8180:8080 -d --link stupefied_colden:kie-wb jboss/kie-server-showcase:latest
$docker ps
CONTAINER ID        IMAGE                              COMMAND                  CREATED             STATUS              PORTS                                            NAMES
a53d82d65c95        jboss/kie-server-showcase:latest   "./start_kie-server.…"   4 seconds ago       Up 2 seconds        0.0.0.0:8180->8080/tcp                           zen_roentgen
033fa996413b        jboss/jbpm-workbench-showcase      "./start_jbpm-wb.sh"     7 minutes ago       Up 7 minutes        0.0.0.0:8001->8001/tcp, 0.0.0.0:8080->8080/tcp   stupefied_colden
```
I just logged into jbpm-wb as admin, build and deployed the sample evaluation project which then showed up in "execution server" and "process definitions" view. I was able to start an instance/task.
I have not tested beyond this point.

**Comment by NullVoxPopuli** [comment]
> "execution server" and "process definitions

where are these?

**Comment by SimonRinguette** [comment]
@NullVoxPopuli I tried it and indeed 7.7.0 fixes the issue. I was not able to import a git project made with 7.5 (but that would require a lot more investigating) but I was able to deploye the sample projects and run them.

This can be closed.

**Comment by NullVoxPopuli** [comment]
I still haven't successfully gotten anything out of the kie-server rest api. :-(

**Comment by SimonRinguette** [comment]
@NullVoxPopuli Actually, the documentation does not expose the 8080 port on the KIEServer this deployment (i'm guessing) is not intended to expose it.

You can expose port 8080 on the kie-server docker to port 8081 on localhost (since you are already using 8080 for the workbench) and access the KieServer at: http://localhost:8081/kie-server/services/rest/server

**Comment by SimonRinguette** [comment]
Using of course the default username/password kieserver/kieserver1!

**Comment by NullVoxPopuli** [comment]
I visit: http://localhost:8180/kie-server/services/rest/server/containers
but, it just shows:
```xml
<response type="SUCCESS" msg="List of created containers">
  <kie-containers/>
</response>
```

And I clicked 'deploy' in the jbpm workbench tool :-\

**Comment by NullVoxPopuli** [comment]
oh man... my issue the whole time was that my link was kie_wb instead of kie-wb.

documentation was wrong. opened an issue here about it: https://github.com/jboss-dockerfiles/drools/issues/38

**Comment by gundan68** [comment]
I have the same problem. I use VM(OS: ubuntu 14.04 ) include two docker containers. one is  JBPM workbench  and the other is Kie server. 

1.JBPM workbench 
   install package: https://download.jboss.org/jbpm/release/7.8.0.Final/jbpm-installer-7.8.0.Final.zip
  start command:
   docker run -d -it --name oz-jbpm --net=oz_net --ip 192.168.250.11 -p 58081:8081  -p 59092:9092   oz-jbpm:7.8

2.Kie Server
install package: https://hub.docker.com/r/jboss/kie-server-showcase/ ( I use this DockerFile to make image)
  start command: 
   docker run -d -it --name exec --net=oz_net --ip 192.168.250.12 -p 58082:8082  kieserver:7.8


These files are my docker files and my wildfy setup files:

[Dockerfile_jbpm.txt](https://github.com/jboss-dockerfiles/jbpm/files/2226022/Dockerfile_jbpm.txt)
[Dockerfile_kieserver.txt](https://github.com/jboss-dockerfiles/jbpm/files/2226025/Dockerfile_kieserver.txt)
[standalone-full-wildfly-11.0.0.Final.xml.txt](https://github.com/jboss-dockerfiles/jbpm/files/2226027/standalone-full-wildfly-11.0.0.Final.xml.txt)
[standalone-full-kie-server.xml.txt](https://github.com/jboss-dockerfiles/jbpm/files/2226029/standalone-full-kie-server.xml.txt)


JBPM-console error logs as follow:

2018-07-24 09:37:58,640 ERROR [org.dashbuilder.exception.ExceptionManager] (default task-9) Can't lookup on specified data set: jbpmProcessInstances: org.dashbuilder.dataset.exception.DataSetLookupException: Can't lookup on specified data set: jbpmProcessInstances
        at org.dashbuilder.dataset.DataSetManagerImpl.lookupDataSet(DataSetManagerImpl.java:156)
        at org.dashbuilder.dataset.DataSetManagerCDI$Proxy$_$$_WeldClientProxy.lookupDataSet(Unknown Source)
        at org.dashbuilder.dataset.service.DataSetLookupServicesImpl.lookupDataSet(DataSetLookupServicesImpl.java:78)
        at org.dashbuilder.dataset.service.DataSetLookupServicesImpl$Proxy$_$$_WeldClientProxy.lookupDataSet(Unknown Source)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jboss.errai.bus.server.io.AbstractRPCMethodCallback.invokeMethodFromMessage(AbstractRPCMethodCallback.java:65)
        at org.jboss.errai.bus.server.io.ValueReplyRPCEndpointCallback.callback(ValueReplyRPCEndpointCallback.java:40)
        at org.jboss.errai.bus.server.io.RemoteServiceCallback.callback(RemoteServiceCallback.java:54)
        at org.jboss.errai.cdi.server.CDIExtensionPoints$2.callback(CDIExtensionPoints.java:448)
        at org.jboss.errai.bus.server.DeliveryPlan.deliver(DeliveryPlan.java:47)
        at org.jboss.errai.bus.server.ServerMessageBusImpl.sendGlobal(ServerMessageBusImpl.java:297)
        at org.jboss.errai.bus.server.SimpleDispatcher.dispatchGlobal(SimpleDispatcher.java:46)
        at org.jboss.errai.bus.server.service.ErraiServiceImpl.store(ErraiServiceImpl.java:96)
        at org.jboss.errai.bus.server.service.ErraiServiceImpl.store(ErraiServiceImpl.java:113)
        at org.jboss.errai.bus.server.servlet.DefaultBlockingServlet.doPost(DefaultBlockingServlet.java:144)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:85)
        at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)
        at io.undertow.websockets.jsr.JsrWebSocketFilter.doFilter(JsrWebSocketFilter.java:130)
        at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
        at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
        at org.uberfire.ext.security.server.SecureHeadersFilter.doFilter(SecureHeadersFilter.java:110)
        at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
        at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
        at org.uberfire.ext.security.server.SecurityIntegrationFilter.doFilter(SecurityIntegrationFilter.java:70)
        at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
        at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
        at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
        at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
        at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
        at org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:131)
        at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
        at io.undertow.server.handlers.DisableCacheHandler.handleRequest(DisableCacheHandler.java:33)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at io.undertow.security.handlers.AuthenticationConstraintHandler.handleRequest(AuthenticationConstraintHandler.java:53)
        at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
        at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
        at io.undertow.servlet.handlers.security.ServletSecurityConstraintHandler.handleRequest(ServletSecurityConstraintHandler.java:59)
        at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
        at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
        at io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
        at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at org.wildfly.extension.undertow.deployment.GlobalRequestControllerHandler.handleRequest(GlobalRequestControllerHandler.java:68)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:292)
        at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:81)
        at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:138)
        at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:135)
        at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
        at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
        at org.wildfly.extension.undertow.security.SecurityContextThreadSetupAction.lambda$create$0(SecurityContextThreadSetupAction.java:105)
        at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1508)
        at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1508)
        at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1508)
        at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1508)
        at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:272)
        at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:81)
        at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:104)
        at io.undertow.server.Connectors.executeRootHandler(Connectors.java:326)
        at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:812)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.kie.server.common.rest.KieServerHttpRequestException: Unable to retrieve input stream of response
        at org.kie.server.common.rest.KieServerHttpRequest.responseStream(KieServerHttpRequest.java:1389)
        at org.kie.server.common.rest.KieServerHttpRequest.responseBuffer(KieServerHttpRequest.java:1407)
        at org.kie.server.common.rest.KieServerHttpRequest.responseBody(KieServerHttpRequest.java:1349)
        at org.kie.server.common.rest.KieServerHttpRequest.access$2100(KieServerHttpRequest.java:117)
        at org.kie.server.common.rest.KieServerHttpRequest$5.body(KieServerHttpRequest.java:1315)
        at org.kie.server.client.impl.AbstractKieServicesClientImpl.createExceptionForUnexpectedResponseCode(AbstractKieServicesClientImpl.java:615)
        at org.kie.server.client.impl.AbstractKieServicesClientImpl.makeHttpPostRequestAndCreateCustomResponse(AbstractKieServicesClientImpl.java:320)
        at org.kie.server.client.impl.AbstractKieServicesClientImpl.makeHttpPostRequestAndCreateCustomResponse(AbstractKieServicesClientImpl.java:300)
        at org.kie.server.client.impl.QueryServicesClientImpl.query(QueryServicesClientImpl.java:969)
        at org.jbpm.workbench.ks.integration.KieServerDataSetProvider.performQuery(KieServerDataSetProvider.java:257)
        at org.jbpm.workbench.ks.integration.KieServerDataSetProvider.lookupDataSet(KieServerDataSetProvider.java:179)
        at org.jbpm.workbench.ks.integration.KieServerDataSetProvider$Proxy$_$$_WeldClientProxy.lookupDataSet(Unknown Source)
        at org.dashbuilder.dataset.DataSetManagerImpl.lookupDataSet(DataSetManagerImpl.java:154)
        ... 71 more
Caused by: java.net.HttpRetryException: cannot retry due to server authentication, in streaming mode
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1674)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
        at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
        at org.kie.server.common.rest.KieServerHttpRequest.responseCode(KieServerHttpRequest.java:1329)
        at org.kie.server.common.rest.KieServerHttpRequest.post(KieServerHttpRequest.java:719)
        at org.kie.server.client.impl.AbstractKieServicesClientImpl$6.doOperation(AbstractKieServicesClientImpl.java:308)
        at org.kie.server.client.impl.AbstractKieServicesClientImpl.invoke(AbstractKieServicesClientImpl.java:804)
        at org.kie.server.client.impl.AbstractKieServicesClientImpl.makeHttpPostRequestAndCreateCustomResponse(AbstractKieServicesClientImpl.java:305)
        ... 77 more
